// <auto-generated />
using System;
using API_Raspberry.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Raspberry.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260404070115_AddNotificationIdentityFields")]
    partial class AddNotificationIdentityFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("API_Raspberry.Model.CourseSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EndTime")
                        .HasColumnType("longtext");

                    b.Property<string>("Room")
                        .HasColumnType("longtext");

                    b.Property<string>("Semester")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StartTime")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CourseSchedule");
                });

            modelBuilder.Entity("API_Raspberry.Model.ExpenseRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ReasonTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReasonTypeId");

                    b.ToTable("expenseRecords");
                });

            modelBuilder.Entity("API_Raspberry.Model.NotificationFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("FilterType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FilterValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("NotificationFilter");
                });

            modelBuilder.Entity("API_Raspberry.Model.PhoneNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AndroidTime")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("App")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AppName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NotificationId")
                        .HasColumnType("longtext");

                    b.Property<string>("NotificationKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NotificationTag")
                        .HasColumnType("longtext");

                    b.Property<string>("Text")
                        .HasColumnType("longtext");

                    b.Property<string>("Time")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("NotificationKey")
                        .IsUnique()
                        .HasFilter("`NotificationKey` IS NOT NULL");

                    b.HasIndex("App", "AndroidTime")
                        .IsUnique()
                        .HasFilter("`AndroidTime` IS NOT NULL");

                    b.ToTable("PhoneNotification");
                });

            modelBuilder.Entity("API_Raspberry.Model.ReasonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ReasonName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("reasonType");
                });

            modelBuilder.Entity("API_Raspberry.Model.ExpenseRecord", b =>
                {
                    b.HasOne("API_Raspberry.Model.ReasonType", "ReasonType")
                        .WithMany()
                        .HasForeignKey("ReasonTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ReasonType");
                });
#pragma warning restore 612, 618
        }
    }
}
